# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mora/projects/QuackGame

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mora/projects/QuackGame

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mora/projects/QuackGame/CMakeFiles /home/mora/projects/QuackGame//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mora/projects/QuackGame/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named quack_game_common

# Build rule for target.
quack_game_common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quack_game_common
.PHONY : quack_game_common

# fast build rule for target.
quack_game_common/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_common.dir/build.make CMakeFiles/quack_game_common.dir/build
.PHONY : quack_game_common/fast

#=============================================================================
# Target rules for targets named quack_game_client

# Build rule for target.
quack_game_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quack_game_client
.PHONY : quack_game_client

# fast build rule for target.
quack_game_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_client.dir/build.make CMakeFiles/quack_game_client.dir/build
.PHONY : quack_game_client/fast

#=============================================================================
# Target rules for targets named quack_game_server

# Build rule for target.
quack_game_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quack_game_server
.PHONY : quack_game_server

# fast build rule for target.
quack_game_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/build
.PHONY : quack_game_server/fast

#=============================================================================
# Target rules for targets named quack_game_editor

# Build rule for target.
quack_game_editor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quack_game_editor
.PHONY : quack_game_editor

# fast build rule for target.
quack_game_editor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_editor.dir/build.make CMakeFiles/quack_game_editor.dir/build
.PHONY : quack_game_editor/fast

#=============================================================================
# Target rules for targets named quack_game_tests

# Build rule for target.
quack_game_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quack_game_tests
.PHONY : quack_game_tests

# fast build rule for target.
quack_game_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_tests.dir/build.make CMakeFiles/quack_game_tests.dir/build
.PHONY : quack_game_tests/fast

#=============================================================================
# Target rules for targets named SDL2pp

# Build rule for target.
SDL2pp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2pp
.PHONY : SDL2pp

# fast build rule for target.
SDL2pp/fast:
	$(MAKE) $(MAKESILENT) -f SDL2pp/CMakeFiles/SDL2pp.dir/build.make SDL2pp/CMakeFiles/SDL2pp.dir/build
.PHONY : SDL2pp/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

client/main.o: client/main.cpp.o
.PHONY : client/main.o

# target to build an object file
client/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_client.dir/build.make CMakeFiles/quack_game_client.dir/client/main.cpp.o
.PHONY : client/main.cpp.o

client/main.i: client/main.cpp.i
.PHONY : client/main.i

# target to preprocess a source file
client/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_client.dir/build.make CMakeFiles/quack_game_client.dir/client/main.cpp.i
.PHONY : client/main.cpp.i

client/main.s: client/main.cpp.s
.PHONY : client/main.s

# target to generate assembly for a file
client/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_client.dir/build.make CMakeFiles/quack_game_client.dir/client/main.cpp.s
.PHONY : client/main.cpp.s

common/constant_rate_loop.o: common/constant_rate_loop.cpp.o
.PHONY : common/constant_rate_loop.o

# target to build an object file
common/constant_rate_loop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_common.dir/build.make CMakeFiles/quack_game_common.dir/common/constant_rate_loop.cpp.o
.PHONY : common/constant_rate_loop.cpp.o

common/constant_rate_loop.i: common/constant_rate_loop.cpp.i
.PHONY : common/constant_rate_loop.i

# target to preprocess a source file
common/constant_rate_loop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_common.dir/build.make CMakeFiles/quack_game_common.dir/common/constant_rate_loop.cpp.i
.PHONY : common/constant_rate_loop.cpp.i

common/constant_rate_loop.s: common/constant_rate_loop.cpp.s
.PHONY : common/constant_rate_loop.s

# target to generate assembly for a file
common/constant_rate_loop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_common.dir/build.make CMakeFiles/quack_game_common.dir/common/constant_rate_loop.cpp.s
.PHONY : common/constant_rate_loop.cpp.s

common/liberror.o: common/liberror.cpp.o
.PHONY : common/liberror.o

# target to build an object file
common/liberror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_common.dir/build.make CMakeFiles/quack_game_common.dir/common/liberror.cpp.o
.PHONY : common/liberror.cpp.o

common/liberror.i: common/liberror.cpp.i
.PHONY : common/liberror.i

# target to preprocess a source file
common/liberror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_common.dir/build.make CMakeFiles/quack_game_common.dir/common/liberror.cpp.i
.PHONY : common/liberror.cpp.i

common/liberror.s: common/liberror.cpp.s
.PHONY : common/liberror.s

# target to generate assembly for a file
common/liberror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_common.dir/build.make CMakeFiles/quack_game_common.dir/common/liberror.cpp.s
.PHONY : common/liberror.cpp.s

common/resolver.o: common/resolver.cpp.o
.PHONY : common/resolver.o

# target to build an object file
common/resolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_common.dir/build.make CMakeFiles/quack_game_common.dir/common/resolver.cpp.o
.PHONY : common/resolver.cpp.o

common/resolver.i: common/resolver.cpp.i
.PHONY : common/resolver.i

# target to preprocess a source file
common/resolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_common.dir/build.make CMakeFiles/quack_game_common.dir/common/resolver.cpp.i
.PHONY : common/resolver.cpp.i

common/resolver.s: common/resolver.cpp.s
.PHONY : common/resolver.s

# target to generate assembly for a file
common/resolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_common.dir/build.make CMakeFiles/quack_game_common.dir/common/resolver.cpp.s
.PHONY : common/resolver.cpp.s

common/resolvererror.o: common/resolvererror.cpp.o
.PHONY : common/resolvererror.o

# target to build an object file
common/resolvererror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_common.dir/build.make CMakeFiles/quack_game_common.dir/common/resolvererror.cpp.o
.PHONY : common/resolvererror.cpp.o

common/resolvererror.i: common/resolvererror.cpp.i
.PHONY : common/resolvererror.i

# target to preprocess a source file
common/resolvererror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_common.dir/build.make CMakeFiles/quack_game_common.dir/common/resolvererror.cpp.i
.PHONY : common/resolvererror.cpp.i

common/resolvererror.s: common/resolvererror.cpp.s
.PHONY : common/resolvererror.s

# target to generate assembly for a file
common/resolvererror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_common.dir/build.make CMakeFiles/quack_game_common.dir/common/resolvererror.cpp.s
.PHONY : common/resolvererror.cpp.s

common/socket.o: common/socket.cpp.o
.PHONY : common/socket.o

# target to build an object file
common/socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_common.dir/build.make CMakeFiles/quack_game_common.dir/common/socket.cpp.o
.PHONY : common/socket.cpp.o

common/socket.i: common/socket.cpp.i
.PHONY : common/socket.i

# target to preprocess a source file
common/socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_common.dir/build.make CMakeFiles/quack_game_common.dir/common/socket.cpp.i
.PHONY : common/socket.cpp.i

common/socket.s: common/socket.cpp.s
.PHONY : common/socket.s

# target to generate assembly for a file
common/socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_common.dir/build.make CMakeFiles/quack_game_common.dir/common/socket.cpp.s
.PHONY : common/socket.cpp.s

editor/main.o: editor/main.cpp.o
.PHONY : editor/main.o

# target to build an object file
editor/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_editor.dir/build.make CMakeFiles/quack_game_editor.dir/editor/main.cpp.o
.PHONY : editor/main.cpp.o

editor/main.i: editor/main.cpp.i
.PHONY : editor/main.i

# target to preprocess a source file
editor/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_editor.dir/build.make CMakeFiles/quack_game_editor.dir/editor/main.cpp.i
.PHONY : editor/main.cpp.i

editor/main.s: editor/main.cpp.s
.PHONY : editor/main.s

# target to generate assembly for a file
editor/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_editor.dir/build.make CMakeFiles/quack_game_editor.dir/editor/main.cpp.s
.PHONY : editor/main.cpp.s

server/acceptor.o: server/acceptor.cpp.o
.PHONY : server/acceptor.o

# target to build an object file
server/acceptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/acceptor.cpp.o
.PHONY : server/acceptor.cpp.o

server/acceptor.i: server/acceptor.cpp.i
.PHONY : server/acceptor.i

# target to preprocess a source file
server/acceptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/acceptor.cpp.i
.PHONY : server/acceptor.cpp.i

server/acceptor.s: server/acceptor.cpp.s
.PHONY : server/acceptor.s

# target to generate assembly for a file
server/acceptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/acceptor.cpp.s
.PHONY : server/acceptor.cpp.s

server/game.o: server/game.cpp.o
.PHONY : server/game.o

# target to build an object file
server/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/game.cpp.o
.PHONY : server/game.cpp.o

server/game.i: server/game.cpp.i
.PHONY : server/game.i

# target to preprocess a source file
server/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/game.cpp.i
.PHONY : server/game.cpp.i

server/game.s: server/game.cpp.s
.PHONY : server/game.s

# target to generate assembly for a file
server/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/game.cpp.s
.PHONY : server/game.cpp.s

server/gameloop.o: server/gameloop.cpp.o
.PHONY : server/gameloop.o

# target to build an object file
server/gameloop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/gameloop.cpp.o
.PHONY : server/gameloop.cpp.o

server/gameloop.i: server/gameloop.cpp.i
.PHONY : server/gameloop.i

# target to preprocess a source file
server/gameloop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/gameloop.cpp.i
.PHONY : server/gameloop.cpp.i

server/gameloop.s: server/gameloop.cpp.s
.PHONY : server/gameloop.s

# target to generate assembly for a file
server/gameloop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/gameloop.cpp.s
.PHONY : server/gameloop.cpp.s

server/main.o: server/main.cpp.o
.PHONY : server/main.o

# target to build an object file
server/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/main.cpp.o
.PHONY : server/main.cpp.o

server/main.i: server/main.cpp.i
.PHONY : server/main.i

# target to preprocess a source file
server/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/main.cpp.i
.PHONY : server/main.cpp.i

server/main.s: server/main.cpp.s
.PHONY : server/main.s

# target to generate assembly for a file
server/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/main.cpp.s
.PHONY : server/main.cpp.s

server/map.o: server/map.cpp.o
.PHONY : server/map.o

# target to build an object file
server/map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/map.cpp.o
.PHONY : server/map.cpp.o

server/map.i: server/map.cpp.i
.PHONY : server/map.i

# target to preprocess a source file
server/map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/map.cpp.i
.PHONY : server/map.cpp.i

server/map.s: server/map.cpp.s
.PHONY : server/map.s

# target to generate assembly for a file
server/map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/map.cpp.s
.PHONY : server/map.cpp.s

server/protocol.o: server/protocol.cpp.o
.PHONY : server/protocol.o

# target to build an object file
server/protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/protocol.cpp.o
.PHONY : server/protocol.cpp.o

server/protocol.i: server/protocol.cpp.i
.PHONY : server/protocol.i

# target to preprocess a source file
server/protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/protocol.cpp.i
.PHONY : server/protocol.cpp.i

server/protocol.s: server/protocol.cpp.s
.PHONY : server/protocol.s

# target to generate assembly for a file
server/protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/protocol.cpp.s
.PHONY : server/protocol.cpp.s

server/receiver.o: server/receiver.cpp.o
.PHONY : server/receiver.o

# target to build an object file
server/receiver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/receiver.cpp.o
.PHONY : server/receiver.cpp.o

server/receiver.i: server/receiver.cpp.i
.PHONY : server/receiver.i

# target to preprocess a source file
server/receiver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/receiver.cpp.i
.PHONY : server/receiver.cpp.i

server/receiver.s: server/receiver.cpp.s
.PHONY : server/receiver.s

# target to generate assembly for a file
server/receiver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/receiver.cpp.s
.PHONY : server/receiver.cpp.s

server/sender.o: server/sender.cpp.o
.PHONY : server/sender.o

# target to build an object file
server/sender.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/sender.cpp.o
.PHONY : server/sender.cpp.o

server/sender.i: server/sender.cpp.i
.PHONY : server/sender.i

# target to preprocess a source file
server/sender.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/sender.cpp.i
.PHONY : server/sender.cpp.i

server/sender.s: server/sender.cpp.s
.PHONY : server/sender.s

# target to generate assembly for a file
server/sender.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/sender.cpp.s
.PHONY : server/sender.cpp.s

server/server.o: server/server.cpp.o
.PHONY : server/server.o

# target to build an object file
server/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/server.cpp.o
.PHONY : server/server.cpp.o

server/server.i: server/server.cpp.i
.PHONY : server/server.i

# target to preprocess a source file
server/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/server.cpp.i
.PHONY : server/server.cpp.i

server/server.s: server/server.cpp.s
.PHONY : server/server.s

# target to generate assembly for a file
server/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/server.cpp.s
.PHONY : server/server.cpp.s

server/session.o: server/session.cpp.o
.PHONY : server/session.o

# target to build an object file
server/session.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/session.cpp.o
.PHONY : server/session.cpp.o

server/session.i: server/session.cpp.i
.PHONY : server/session.i

# target to preprocess a source file
server/session.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/session.cpp.i
.PHONY : server/session.cpp.i

server/session.s: server/session.cpp.s
.PHONY : server/session.s

# target to generate assembly for a file
server/session.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/session.cpp.s
.PHONY : server/session.cpp.s

server/sessions_handler.o: server/sessions_handler.cpp.o
.PHONY : server/sessions_handler.o

# target to build an object file
server/sessions_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/sessions_handler.cpp.o
.PHONY : server/sessions_handler.cpp.o

server/sessions_handler.i: server/sessions_handler.cpp.i
.PHONY : server/sessions_handler.i

# target to preprocess a source file
server/sessions_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/sessions_handler.cpp.i
.PHONY : server/sessions_handler.cpp.i

server/sessions_handler.s: server/sessions_handler.cpp.s
.PHONY : server/sessions_handler.s

# target to generate assembly for a file
server/sessions_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_server.dir/build.make CMakeFiles/quack_game_server.dir/server/sessions_handler.cpp.s
.PHONY : server/sessions_handler.cpp.s

tests/foo.o: tests/foo.cpp.o
.PHONY : tests/foo.o

# target to build an object file
tests/foo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_tests.dir/build.make CMakeFiles/quack_game_tests.dir/tests/foo.cpp.o
.PHONY : tests/foo.cpp.o

tests/foo.i: tests/foo.cpp.i
.PHONY : tests/foo.i

# target to preprocess a source file
tests/foo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_tests.dir/build.make CMakeFiles/quack_game_tests.dir/tests/foo.cpp.i
.PHONY : tests/foo.cpp.i

tests/foo.s: tests/foo.cpp.s
.PHONY : tests/foo.s

# target to generate assembly for a file
tests/foo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quack_game_tests.dir/build.make CMakeFiles/quack_game_tests.dir/tests/foo.cpp.s
.PHONY : tests/foo.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... SDL2pp"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... quack_game_client"
	@echo "... quack_game_common"
	@echo "... quack_game_editor"
	@echo "... quack_game_server"
	@echo "... quack_game_tests"
	@echo "... client/main.o"
	@echo "... client/main.i"
	@echo "... client/main.s"
	@echo "... common/constant_rate_loop.o"
	@echo "... common/constant_rate_loop.i"
	@echo "... common/constant_rate_loop.s"
	@echo "... common/liberror.o"
	@echo "... common/liberror.i"
	@echo "... common/liberror.s"
	@echo "... common/resolver.o"
	@echo "... common/resolver.i"
	@echo "... common/resolver.s"
	@echo "... common/resolvererror.o"
	@echo "... common/resolvererror.i"
	@echo "... common/resolvererror.s"
	@echo "... common/socket.o"
	@echo "... common/socket.i"
	@echo "... common/socket.s"
	@echo "... editor/main.o"
	@echo "... editor/main.i"
	@echo "... editor/main.s"
	@echo "... server/acceptor.o"
	@echo "... server/acceptor.i"
	@echo "... server/acceptor.s"
	@echo "... server/game.o"
	@echo "... server/game.i"
	@echo "... server/game.s"
	@echo "... server/gameloop.o"
	@echo "... server/gameloop.i"
	@echo "... server/gameloop.s"
	@echo "... server/main.o"
	@echo "... server/main.i"
	@echo "... server/main.s"
	@echo "... server/map.o"
	@echo "... server/map.i"
	@echo "... server/map.s"
	@echo "... server/protocol.o"
	@echo "... server/protocol.i"
	@echo "... server/protocol.s"
	@echo "... server/receiver.o"
	@echo "... server/receiver.i"
	@echo "... server/receiver.s"
	@echo "... server/sender.o"
	@echo "... server/sender.i"
	@echo "... server/sender.s"
	@echo "... server/server.o"
	@echo "... server/server.i"
	@echo "... server/server.s"
	@echo "... server/session.o"
	@echo "... server/session.i"
	@echo "... server/session.s"
	@echo "... server/sessions_handler.o"
	@echo "... server/sessions_handler.i"
	@echo "... server/sessions_handler.s"
	@echo "... tests/foo.o"
	@echo "... tests/foo.i"
	@echo "... tests/foo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

