#ifndef DUCK_DEFS_H
#define DUCK_DEFS_H

#define DUCK_DEFAULT_HEIGHT 24
#define DUCK_DEFAULT_WIDTH 16

#define DUCK_BENT_DOWN_HEIGHT 13
#define DUCK_BENT_DOWN_WIDTH 22

#define X_VELOCITY 4
#define Y_VELOCITY_INITIAL 0
#define Y_VELOCITY_ON_JUMP 16
#define Y_VELOCITY_FLAPPING -2
#define Y_VELOCITY_FALL 1

#endif // DUCK_DEFS_H