#ifndef SIZE_DEFS_PROJECTILES_H
#define SIZE_DEFS_PROJECTILES_H

#define PROJECTILE_GUN_WIDTH 8
#define PROJECTILE_GUN_HEIGHT 8

#define PROJECTILE_GRENADE_WIDTH 15
#define PROJECTILE_GRENADE_HEIGHT 15

#endif // SIZE_DEFS_PROJECTILES_H