gun:
  ammo:
    pew_pew_laser: 12
    laser_rifle: 10
    ak: 30
    dueling_pistol: 1
    cowboy_pistol: 6
    magnum: 6
    shotgun: 2
    sniper: 3

  velocity_projectile:
    pew_pew_laser: 10
    laser_rifle: 20
    ak: 20
    dueling_pistol: 10
    cowboy_pistol: 10
    magnum: 10
    shotgun: 10
    sniper: 10
