#ifndef FIGURE_SIZES_H
#define FIGURE_SIZES_H

// Duck
#define DUCK_HEIGHT 32
#define DUCK_WIDTH 32
#define DUCK_WITH_GUN_Y_DIRECTION 11
#define DUCK_WITH_GUN_RIGHT_DIRECTION 10
#define DUCK_WITH_GUN_LEFT_DIRECTION 5

// Gun
#define GUN_HEIGHT 16
#define GUN_WIDTH 16

#endif // FIGURE_SIZES_H