#ifndef FIGURE_SIZES_H
#define FIGURE_SIZES_H

// Duck
#define DUCK_HEIGHT 32
#define DUCK_WIDTH 32
#define DUCK_WITH_GUN_Y_DIRECTION 11
#define DUCK_WITH_GUN_RIGHT_DIRECTION 10
#define DUCK_WITH_GUN_LEFT_DIRECTION -5

// Gun
#define GUN_HEIGHT 16
#define GUN_WIDTH 26

// Projectile
#define PROJECTILE_HEIGHT 8
#define PROJECTILE_WIDTH 8

#endif // FIGURE_SIZES_H