#ifndef SIZE_DEFS_GUNS_H
#define SIZE_DEFS_GUNS_H

#define AK_WIDTH 25
#define AK_HEIGHT 10

#define BANANA_WIDTH 15
#define BANANA_HEIGHT 15

#define COWBOY_PISTOL_WIDTH 20
#define COWBOY_PISTOL_HEIGHT 10

#define DUELING_PISTOL_WIDTH 20
#define DUELING_PISTOL_HEIGHT 10

#define GRENADE_WIDTH 15
#define GRENADE_HEIGHT 15

#define MAGNUM_WIDTH 20
#define MAGNUM_HEIGHT 10

#define PEW_PEW_LASER_WIDTH 20
#define PEW_PEW_LASER_HEIGHT 10

#define SHOTGUN_WIDTH 25
#define SHOTGUN_HEIGHT 10

#define SNIPER_WIDTH 20
#define SNIPER_HEIGHT 10

#endif // SIZE_DEFS_GUNS_H